version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  test-db:
    image: postgres:latest
    container_name: test-db_app
    env_file:
      - .env-non-dev
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    command: -p 6000
    expose:
      - 6000


  redis:
    image: redis:latest
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db-test
      - redis