version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    container_name: test-db_app
    env_file:
      - .env
    command: -p 6000
    expose:
      - 6000


  redis:
    image: redis:latest
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test-db
      - redis
volumes:
  db-data:
